branches:
- develop

scripts:
- ../webchannel-ci/uss/setup/repos.rb
- ../webchannel-ci/uss/setup/uss.rb
- ../webchannel-ci/uss/setup/wireline-mock-services.rb
- ../webchannel-ci/uss/run/phpunit.rb
- ../webchannel-ci/uss/archive/results.rb
