---
- name: "Directory Exists | {{ mci_log_root }}"
  file:
    state: directory
    path: "{{ mci_log_root }}"
    owner: "{{ mci_user }}"
    group: admin
    mode: 0775
  tags:
    - directory-structure
    - logging
    - mci
