---
- name: Upload Config | monit | mci-server
  template:
    src: etc/monit/conf.d/mci-server
    dest: /etc/monit/conf.d/mci-server
  notify: Reload Service | monit
  tags:
    - mci
    - mci-server
    - monit

- name: Upload Config | monit | mci-worker
  template:
    src: etc/monit/conf.d/mci-worker
    dest: /etc/monit/conf.d/mci-worker
  notify: Reload Service | monit
  tags:
    - mci
    - mci-worker
    - monit

- name: Trigger All Callbacks
  meta: flush_handlers

- name: Confirm Monitoring | mci-server
  monit:
    state: present
    name: mci-server
  tags:
    - mci
    - mci-server
    - monit

- name: Confirm Monitoring | mci-worker
  monit:
    state: present
    name: mci-worker
  tags:
    - mci
    - mci-worker
    - monit

